# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Richard Kellermeyer
email: your-email@example.com
bio: >- # this means to ignore newlines until "baseurl:"
  01001001 00100000 01100010 01100101 01101100 01101001 01100101 01110110 01100101 00100000 01101001 01101110 00100000 01110100 01101000 01100101 00100000 01110000 01101111 01110111 01100101 01110010 00100000 01101111 01100110 00100000 01110100 01100101 01100011 01101000 01101110 01101111 01101100 01101111 01100111 01111001 00100000 01110100 01101111 00100000 01100001 01100100 01110110 01100001 01101110 01100011 01100101 00100000 01100001 01101110 01100100 00100000 01100101 01101110 01101000 01100001 01101110 01100011 01100101 00100000 01101100 01101001 01110110 01100101 01110011 00100000 01100010 01111001 00100000 01101001 01101101 01110000 01110010 01101111 01110110 01101001 01101110 01100111 00100000 01100011 01101111 01101110 01110011 01100011 01101001 01101111 01110101 01110011 01101110 01100101 01110011 73 2C 00100000 01100001 01110111 01100001 01110010 01100101 01101110 01100101 01110011 73 2C 00100000 01100001 01101110 01100100 00100000 01100101 01101101 01110000 01100001 01110100 01101000 79 2E
description: >- # this means to ignore newlines until "baseurl:"
  Hi, I'm Richard Kellermeyer, an Application Architect with a passion for using technology to simplify and improve our lives. With over 20 years in the industry, I've seen the impact well-crafted software can have on businesses of all sizes.  My experience spans the full spectrum, from architecting large-scale enterprise platforms to building user-friendly marketing websites. I'm equally comfortable leading teams and diving into the code myself, always striving for innovative solutions that deliver real value.  When I'm not immersed in the digital world, you can usually find me in the kitchen, experimenting with new recipes. Let's connect and discuss how my diverse skillset can help your business thrive.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: TechSuperSaiyan
github_username:  rkellermeyer

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Defaults
defaults:
  # - scope:
  #     path: ""
  #     type: "authors"
  #   values:
  #     layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
