# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Richard Kellermeyer
email: your-email@example.com
bio: >- # this means to ignore newlines until "baseurl:"
  I believe in the power of technology to transform businesses and improve lives. My vision is to leverage my expertise to create solutions that are not only technically sound but also user-centric and impactful. I am committed to staying at the forefront of technological advancements, always looking for ways to innovate and improve. Let’s build the future together.
description: >- # this means to ignore newlines until "baseurl:"
  My name is Richard Kellermeyer, and I'm a firm believer that technology should simplify our lives, not complicate them. As an Application Architect with a wealth of experience, I've seen the transformative power of well-crafted software. I'm dedicated to leading teams towards creating solutions that are both innovative and user-friendly. When I'm not immersed in the digital world, you'll likely find me whipping up something in the kitchen. I'm excited to connect and share my expertise with you!
baseurl: "/Me" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: TechSuperSaiyan
github_username:  rkellermeyer

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Defaults
defaults:
  # - scope:
  #     path: ""
  #     type: "authors"
  #   values:
  #     layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
